### ISSUE TITLE
half_win_duration issue

### ISSUE THREAD

**Issue by Fildo7525** [karb94/neoscroll.nvim#104]
After update I get this error after entering 'zz'
```
E5108: Error executing lua: ...al/share/nvim/lazy/neoscroll.nvim/lua/neoscroll/init.lua:269: attempt to perform arithmetic on local 'half_win_duration' (a table value)
stack traceback:
        ...al/share/nvim/lazy/neoscroll.nvim/lua/neoscroll/init.lua:269: in function 'zz'
        ...al/share/nvim/lazy/neoscroll.nvim/lua/neoscroll/init.lua:357: in function <...al/share/nvim/lazy/neoscroll.nvim/lua/neoscroll/init.lua:357
```

**Comment by karb94** [comment]
Fixed by c9e5e8f

**Comment by Le-Kat** [comment]
Hi, I'm on version `a731f66` but I'm still having this issue.
Using this minimal setup (with Lazy.nvim)

```lua
return {
	"karb94/neoscroll.nvim",
	event = "VeryLazy",
	config = function()
		local neoscroll = require ("neoscroll")
		neoscroll.setup ({ mappings = {} })
		local modes = { 'n', 'v', 'x' }
		local keymaps = {
			["G"]     = function() neoscroll.G({ half_screen_duration = 250 }) end;
			["gg"]    = function() neoscroll.gg({ half_screen_duration = 250 }) end;
		}
		for key, func in pairs (keymaps) do
			vim.keymap.set (modes, key, func)
		end
	end,
}
```

I get the error

```lua
E5108: Error executing lua: ...al/share/nvim/lazy/neoscroll.nvim/lua/neoscroll/init.lua:319: attempt to perform arithmetic on local 'half_win_duration' (a table value)
stack traceback:
        ...al/share/nvim/lazy/neoscroll.nvim/lua/neoscroll/init.lua:319: in function 'G'
        /home/le3kat/.config/nvim/lua/plugins/scroll.lua:12: in function </home/le3kat/.config/nvim/lua/plugins/scroll.lua:12>
```

For both the `G` and `gg` keys
