### ISSUE TITLE
bug: error if there is only one line remains to be scrolled

### ISSUE THREAD

**Issue by bmorashad** [karb94/neoscroll.nvim#97]
**Issue:**

If there is only one line remaining to be scrolled when scrolled it throws the below error, although scrolling works.

```
Error executing vim.schedule lua callback: ...al/share/nvim/lazy/neoscroll.nvim/lua/neoscroll/init.lua:91: Direction cannot be zero
stack traceback:
        [C]: in function 'error'
        ...al/share/nvim/lazy/neoscroll.nvim/lua/neoscroll/init.lua:91: in function 'who_scrolls'
        ...al/share/nvim/lazy/neoscroll.nvim/lua/neoscroll/init.lua:313: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Steps to Reproduce**

- Go to the line before the last line of the file (**i.e:** 19th line if there are 20 lines)
-  Scroll with {'scroll', { 'vim.wo.scroll', 'true', '50'}

Using Linux

**Comment by Joarell** [comment]
Hi @bmorashad!
I had the same issue. I just comment the lines 91, 92, and 93 over plugin file path:`.local/share/nvim/lazy/neoscroll.nvim/lua/neoscroll/init.lua:91`.
There is `if` statement and apparently it can be disposal.

**Comment by sadtab** [comment]
Same here

**Comment by karb94** [comment]
Hey, apologies, I was doing quite a bit of refactoring for upcoming features and I probably messed something up. The if statement is there to indicate that something went wrong so better not remove it. I cannot reproduce the issue but I think I fixed it. Can you pull the latest changes and let me know?

**Comment by Joarell** [comment]
Dear @karb94, I appreciate your prompt reply, however the problem remains.
I have a quite big `CSS` file, and when a try to use `ctrl+d` to roll it, the issue popup. 
I am not even close to the end of the file.
When a comment those lines with the `if` statement, I didn't get any `errors` the plugin goes pretty well.

![image](https://github.com/karb94/neoscroll.nvim/assets/42722369/c32f566f-7bce-4f7d-81f5-47582f6e3e09)

**Comment by karb94** [comment]
Can you try again with the latest commit? I appreciate that removing the `error()` call will remove the error you are seeing but the reason it complaints is because that function shouldn't be getting a value of zero as the direction argument. If I don't solve the root cause now this will lead to other hard to debug issues down the line..

**Comment by karb94** [comment]
Also, does this happen at the beginning of the scroll or at the end? Do you manage to scroll any number of lines before you get the error?

**Comment by Joarell** [comment]
Dear @karb94, I have updated it, but the issue still the same.
I got you. It's a little strange because I am rolling with the `ctrl + d`, and I have many lines down in the file and the `error` popup.

As you can see on my last screenshot, I'm at the middle of the file, rolling with `ctrl + d`.

**Comment by Joarell** [comment]
In addition, I'm using the `Neovim nightly`.

**Comment by karb94** [comment]
are you using default settings? I'm on `Neovim 0.9.5` but I doubt it matters here. Try again with the latest changes. I'm very surprised you manage to trigger this error so many times. Any other hints of when this error is triggered would be appreciate it.

**Comment by Joarell** [comment]
My config:
```lua
{
 'karb94/neoscroll.nvim',
  config = function()
   require("neoscroll").setup()
  end,
}
```

**Comment by Joarell** [comment]
So, just when I try to scroll with `ctrl + d` over a `CSS` file, I got many `errors`.
When I open any other file, I got the `error` when I hit the end of the file.

**Comment by karb94** [comment]
Does this error only show up with `<c+d>`/`<c-u>`? What number do you get if you run `:=vim.wo.scroll`?

**Comment by Joarell** [comment]
I got the same `error`, when I hit the top of the file using `ctrl + u`.
When a run `:=vim.wo.scroll` I got `55`.

**Comment by JohnWickzzz** [comment]
I use the neovim 0.9.5 and get the same error(occasional, no pattern).
When run :=vim.wo.scroll I got 26.

**Comment by karb94** [comment]
Can anyone try to bisect the offending commit? I'm pressume it's d48b336 but would be good get confirmation as I'm having some trouble reproducing this.

**Comment by JohnWickzzz** [comment]
> Can anyone try to bisect the offending commit? I pressume it's [d48b336](https://github.com/karb94/neoscroll.nvim/commit/d48b336b96797a6accc65ee6585c59ab662b6d79) but would be good get confirmation as I'm having some trouble reproducing this.

From my personal simple test, d48b336 will occur error, the previous commit https://github.com/karb94/neoscroll.nvim/commit/c48f15b11877df2cfc5c39666fb8a2524df13bec no problem.

**Comment by karb94** [comment]
I think this might have been a bug for quite a while but we are aware of it now because I've put a check for it. Could someone do me a favour and roll back to c48f15b and add the following if statement at the start of the `who_scrolls()` definition in `lua/neoscroll/init.lua`:

```lua
  if direction == 0 then
    error("Direction cannot be zero")
  end
```
If you still see the error poping up this would mean that there's nothing wrong with the recent commits I made and would save me a lot of debugging time <3.

**Comment by patgro1** [comment]
On my side, the latest commit did not fix it either! Rolled it back to C48f15b and got no error. Added the snippet and it is still ok.

**Comment by karb94** [comment]
After doing some digging I managed to trigger the error if I set a really small animation time (<10ms). I think it is due to a race condition when stopping the timer of the callback. My guess is that old systems will trigger the error more easily. In the last commit I prioritised to stop the timer as soon as possible and also check that the `lines_to_scroll` are not already zero before calling `who_scrolls()`. Please give it a try.

**Comment by pedro757** [comment]
@karb94 here's how to reproduce:

1. In a big file (many rows) hit multiple times `<c-d>`
2. While it's scrolling down smoothly hit `G` to go to the end of a file.

You have to hit capital G while it's doing its thing....

**Comment by karb94** [comment]
Hopefully the fix worked for everyone. Closing the issue.

**Comment by bmorashad** [comment]
Thanks guys, apologies for being late to the thread, it works without any issues now

**Comment by Joarell** [comment]
Sorry for being late!
I would like to thank everyone and special @karb94 for all efforts.
Now is working perfectly!
