### ISSUE TITLE
Animation continues in new window after switching during animation

### ISSUE THREAD

**Issue by vilari-mickopf** [karb94/neoscroll.nvim#99]
When I am using for example ctrl-f to scroll through the current buffer and switch to a split window in the middle of the animation, the animation continues in that window. Is it possible to stop the animation upon switching windows?

**Comment by karb94** [comment]
This should be fixed now

**Comment by vilari-mickopf** [comment]
Hmm still happens on commit @e7865771

https://drive.google.com/file/d/1yEo__Yl_jM6IIFX0f9eR7Uq4uJJ0eUXl/view?usp=sharing

I am scrolling left window, and switching to the right one in middle of animation.

**Comment by karb94** [comment]
Yeah, sorry. There's still some changes to make for it to be fixed. I'll push the real fix soon.

**Comment by karb94** [comment]
Should be fixed now
